version: 3

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: cd-nginx
        ports:
            -   "8080:80"
        volumes:
            -   ./src:/var/www
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
            -   mysql
        networks:
            -   laravel

    mysql:
        image: mysql:5.7.22
        container_name: cd-mysql
        restart: unless-stopped
        tty: true
        ports:
            -   "3306:3306"
        environment:
            MYSQL_DATABASE: content-dumper
            MYSQL_USER: cd-user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            -   ./src:/var/www
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            -   laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cd-php
        volumes:
            -   ./src:/var/www
        ports:
            -   "9000:9000"
        networks:
            -   laravel